version: "3"
services:
  nextjs:
    image: node:22-alpine
    container_name: smartcraze-portfolio
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
